name: Deploy Backend

on:
  push:
    branches:
      - master
    paths:
      - 'server_net/**'
      - 'Dockerfile'
      - 'docker-compose.yml'
      - '.github/workflows/deploy.yml'

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Pull Code and Restart Services on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            TARGET_DIR="/opt/1panel/apps/danmu-tools"

            # 如果目录不存在则初始化仓库
            if [ ! -d "$TARGET_DIR/.git" ]; then
              sudo mkdir -p "$TARGET_DIR"
              sudo chown -R $(whoami):$(whoami) "$TARGET_DIR"
              git clone ${{ secrets.REPO_URL }} "$TARGET_DIR"
            else
              cd "$TARGET_DIR"
              git pull origin master
            fi

            cd "$TARGET_DIR"

            # Restart Docker Containers
            sudo docker-compose up --build -d
            sudo docker image prune -f
